

main.out: Main.o AirBender.o FireBender.o WaterBender.o EarthBender.o nonBender.o Persona.o Benders.o PoderEspecial.o Ofensivo.o Defensivo.o Curativo.o Invocacion.o
	g++ Main.o AirBender.o FireBender.o WaterBender.o EarthBender.o nonBender.o Persona.o Benders.o PoderEspecial.o Ofensivo.o Defensivo.o Curativo.o Invocacion.o -o main.out


main.o: Main.cpp AirBender.cpp FireBender.cpp WaterBender.cpp EarthBender.cpp nonBender.cpp Persona.cpp Benders.cpp PoderEspecial.cpp Ofensivo.cpp Defensivo.cpp Curativo.cpp Invocacion.cpp
	g++ Main.cpp


